config/routes.rb
BootstrapPrototyping::Application.routes.draw do

  get 'ajax/switch_mode'
  
  match 'candidate_signup'                      => 'shareable#candidate_signup'
  match 'candidate_profile'                     => 'shareable#candidate_profile'
  match 'candidate_profile_public'              => 'shareable#candidate_profile_public'
  match 'candidate_profile_you_email'           => 'shareable#candidate_profile_you_email'
  match 'candidate_profile_you_social'          => 'shareable#candidate_profile_you_social'
  match 'candidate_profile_others'              => 'shareable#candidate_profile_others'
  match 'candidate_profile_social_share_you'    => 'shareable#candidate_profile_social_share_you'
  match 'candidate_profile_email_share_you'     => 'shareable#candidate_profile_email_share_you'
  match 'candidate_profile_social_share_others' => 'shareable#candidate_profile_social_share_others'
  match 'candidate_profile_email_share_others'  => 'shareable#candidate_profile_email_share_others'
  match 'candidate_conversations'               => 'shareable#candidate_conversations'
  match 'candidate_conversations2'              => 'shareable#candidate_conversations2'
  match 'candidate_conversations3'              => 'shareable#candidate_conversations3'
  match 'candidate_conversations4'              => 'shareable#candidate_conversations4'
  match 'candidate_sharings'                    => 'shareable#candidate_sharings'
  match 'candidate_sharings2'                   => 'shareable#candidate_sharings2'
  match 'candidate_sharings3'                   => 'shareable#candidate_sharings3'
  match 'candidate_matches'                     => 'shareable#candidate_matches'
  match 'candidate_matches2'                    => 'shareable#candidate_matches2'
  match 'candidate_matches3'                    => 'shareable#candidate_matches3'
  match 'candidate_matches4'                    => 'shareable#candidate_matches4'
  match 'candidate_isnt_interested'             => 'shareable#candidate_isnt_interested'
  match 'candidate_says_yes'                    => 'shareable#candidate_says_yes'
  match 'candidate_says_no'                     => 'shareable#candidate_says_no'
  match 'recruiter_signup'                      => 'shareable#recruiter_signup'
  match 'recruiter_profile'                     => 'shareable#recruiter_profile'
  match 'recruiter_says_yes'                    => 'shareable#recruiter_says_yes'
  match 'recruiter_says_no'                     => 'shareable#recruiter_says_no'
  match 'recruiter_starts_discussion'           => 'shareable#recruiter_starts_discussion'
  match 'recruiter_isnt_interested'             => 'shareable#recruiter_isnt_interested'
  match 'recruiter_profile_1_public'            => 'shareable#recruiter_profile_1_public'
  match 'recruiter_profile_1_others'            => 'shareable#recruiter_profile_1_others'
  match 'recruiter_profile_1_you'               => 'shareable#recruiter_profile_1_you'
  match 'recruiter_profile_2_public'            => 'shareable#recruiter_profile_2_public'
  match 'recruiter_profile_3_public'            => 'shareable#recruiter_profile_3_public'
  match 'recruiter_profile_4_public'            => 'shareable#recruiter_profile_4_public'
  match 'recruiter_conversations'               => 'shareable#recruiter_conversations'
  match 'recruiter_conversations2'              => 'shareable#recruiter_conversations2'
  match 'recruiter_conversations3'              => 'shareable#recruiter_conversations3'
  match 'recruiter_conversations4'              => 'shareable#recruiter_conversations4'
  match 'recruiter_sharings'                    => 'shareable#recruiter_sharings'
  match 'recruiter_sharings2'                   => 'shareable#recruiter_sharings2'
  match 'recruiter_sharings3'                   => 'shareable#recruiter_sharings3'

  root :to => 'pages#dashboard'
end

app/controllers/shareable_controller.rb
class ShareableController < ApplicationController
  
  before_filter       :set_titles
  before_filter       :signup_candidate, :only => :candidate_profile
  before_filter       :signup_recruiter, :only => :recruiter_profile
  before_filter       :candidate_demo,   :only => :candidate_signup
  before_filter       :recruiter_demo,   :only => :recruiter_signup
  skip_before_filter  :verify_authenticity_token
  
  def candidate_profile
    flash.now[:success] = params[:success] unless params[:success].nil?
  end
  
  def candidate_profile_email_share_you
    @default_message = "Hi, I'm really keen to work for your company and would love to go over a few ideas together soon."
  end
  
  def candidate_profile_social_share_you
    @default_message = "Hi everyone, I'm looking for work these days and was wondering if you might know of someone interested? Share my profile if so!"
  end
  
  def candidate_profile_you_email
    @default_message = "Hi, I'm really keen to work for your company and would love to go over a few ideas together soon."
    session[:you] = params[:you] unless params[:you].nil?
  end
  
  def candidate_profile_you_social
    @default_message = "Hi everyone, I'm looking for work these days and was wondering if you might know of someone interested? Share my profile if so!"
    session[:you] = params[:you] unless params[:you].nil?
  end
  
  def candidate_profile_public
    flash.now[:success] = params[:success] unless params[:success].nil?
  end
  
  def candidate_profile_email_share_others
    @default_message = "Hi, I was looking at this profile and thought you might be interested. What do you think?"
  end
  
  def candidate_profile_social_share_others
    @default_message = "Hi, I was looking at this profile and thought you might be interested. What do you think?"
  end
  
  def candidate_profile_others
    @default_message = "Hi, I was looking at this profile and thought you might be interested. What do you think?"
    session[:sharer] = params[:sharer] unless params[:sharer].nil?
    @from_path = (params[:from_path].nil? ? candidate_profile_path : params[:from_path])
  end

  def recruiter_profile
    flash.now[:success] = params[:success] unless params[:success].nil?
  end
  
  private
    
    def set_titles
      @page_title = 'Prototypes'
      @page_subtitle = 'shareable profile'
    end
  
    def signup_candidate
      if params[:candidate]
        if params[:candidate][:full_name].empty?
          session[:candidate] = default_candidate
        else
          session[:candidate] = params[:candidate]
          session[:candidate][:pic] = 'default_user.jpg'
        end
      end      
      session[:recruiter] = default_recruiter if session[:candidate_demo]
    end

    def default_candidate
      if session[:candidate_demo]
        { :pic => 'wansa.jpg', :full_name => 'Wansa Sooksomwat', :city => 'Amsterdam', :country => 'Netherlands', 
        :role => 'Retail Sales', :company => 'Esprit', :experience => '1', 
        :education => 'HBO Bachelor in Communication & Media', 
        :pro_skill_1 => { :name => 'External communication', :level => 'advanced'},
        :pro_skill_2 => { :name => 'Event planning', :level => 'advanced'},
        :pro_skill_3 => { :name => 'Writing', :level => 'intermediate',},
        :pro_star => 'candidate_pro_skill_star_2',
        :inter_skill_1 => { :name => 'Good team mate', :level => 'expert'},
        :inter_skill_2 => { :name => 'Attention to details', :level => 'intermediate'},
        :inter_skill_3 => { :name => 'Organization', :level => 'intermediate'},
        :inter_star => 'candidate_inter_skill_star_1',
        :catchphrase => "Communications isn't what a company says, it's everything else it does." }
      elsif session[:recruiter_demo]
        { :pic => 'carole.jpg', :full_name => 'Carole Dhelens', :city => 'Marseille', :country => 'France', 
        :role => 'Pharmacist resident', :company => 'Hopital de Marseille', :experience => '2', 
        :education => 'PhD in Pharmacy', 
        :pro_skill_1 => { :name => 'Team working', :level => 'advanced'},
        :pro_skill_2 => { :name => 'Patient pool management', :level => 'beginner'},
        :pro_skill_3 => { :name => 'Writing', :level => 'expert'},
        :pro_star => 'candidate_pro_skill_star_3',
        :inter_skill_1 => { :name => 'Hard worker', :level => 'expert'},
        :inter_skill_2 => { :name => 'Organization', :level => 'intermediate'},
        :inter_skill_3 => { :name => 'Patience', :level => 'intermediate'},
        :inter_star => 'candidate_inter_skill_star_1',
        :catchphrase => "I've almost finished my complete pharmacist studies, and I'm looking for a first fulltime job." }
      end
    end
    
    def candidate_demo
      session[:candidate_demo] = true
      session[:recruiter_demo] = false
      session[:recruiter] = nil unless session[:recruiter].nil?
    end

    def signup_recruiter
      if params[:recruiter]
        if params[:recruiter][:full_name].empty?
          session[:recruiter] = default_recruiter
        else
          session[:recruiter] = params[:recruiter]
          session[:recruiter][:pic] = 'default_user.jpg'
        end
      end
      session[:candidate] = default_candidate if session[:recruiter_demo]
    end

    def default_recruiter
      { :pic => 'dom.jpg', :full_name => 'Dominic Matheron', :company => 'Viadeo', :city => 'Amsterdam',
        :country => 'Netherlands', 
        :role_1 => { :name => 'Programmers', :level => 'required' }, 
        :role_2 => { :name => 'Designers', :level => 'intermediate' }, 
        :role_3 => { :name => 'Copywriters', :level => 'not_a_priority' },
        :quality_1 => { :name => 'Honesty', :level => 'urgent' }, 
        :quality_2 => { :name => 'Friendliness', :level => 'required' }, 
        :quality_3 => { :name => 'Punctuality', :level => 'intermediate' }, 
        :quality_star => 'recruiter_quality_star_1', :flexible_1 => 'Education',
        :profile_1 => { :title => 'Graphic Designer', :city => 'Amsterdam', :country => 'Netherlands', :experience => '5yrs',
                        :education => 'HBO or similar degree', :skill_1 => 'Visual Design', :skill_2 => 'Interaction Design',
                        :skill_3 => 'Quick Prototyping'},
        :profile_2 => { :title => 'Mobile Developer', :city => 'Amsterdam', :country => 'Netherlands', :experience => '2yrs',
                        :education => 'Bachelor in sone serious school', :skill_1 => 'iOS', :skill_2 => 'Android',
                        :skill_3 => 'Extremely Rigorous', :star => 'recruiter_profile_2_star_3'},
        :profile_3 => { :title => 'Project Manager', :city => 'Paris', :country => 'France', :experience => '5-8y',
                        :education => 'Experience is the key here', :skill_1 => 'Experienced at Scaling', :skill_2 => 'Agile',
                        :skill_3 => 'Open to oustide input', :star => 'recruiter_profile_3_star_3'},
        :profile_4 => { :title => 'Italian Copywriter', :city => 'Paris', :country => 'France', :experience => '1yr',
                        :education => 'Master in Translation', :skill_1 => 'Native Speaker', :skill_2 => 'Intelligent',
                        :skill_3 => 'Flexible', :star => 'recruiter_profile_4_star_1'} }
    end

    def recruiter_demo
      session[:candidate_demo] = false
      session[:recruiter_demo] = true
      session[:candidate] = default_candidate     
    end
end

app/helpers/shareable_helper.rb
module ShareableHelper
  
  def candidate_demo?
    session[:candidate_demo] == true
  end
  
  def recruiter_demo?
    session[:recruiter_demo] == true
  end
end

app/views/shareable/candidate_profile_others.haml
= render 'menu_candidate'

.row
  .span5
    .card
      .row
        .span4.well
          .row
            .span1
              = link_to image_tag(session[:candidate][:pic]), candidate_profile_public_path
            .span3
              %h3 
                = session[:candidate][:full_name]
              %p
                = session[:candidate][:city]+', '+session[:candidate][:country]
              %p
                = session[:candidate][:role].to_s+' at '+session[:candidate][:company]
      .row
        .span1.well
          %h6
            Experience
          .gigantic 
            = session[:candidate][:experience] == 1.to_s ? '1 yr' : session[:candidate][:experience].to_s+'yrs'
        .span3.well{ :style => 'min-height:92px; padding-right:0' }
          %h6 
            Education
          .lead 
            = session[:candidate][:education]
      .row
        .span4.well{ style: 'padding-bottom:0' }
          %h6
            Skills
          .lead
            .row
              .span3
                = session[:candidate][:pro_skill_1][:name]
                - if session[:candidate][:pro_star] == 'candidate_pro_skill_star_1'
                  .icon-star
              .span1
                = render 'progress_bar', :level => session[:candidate][:pro_skill_1][:level]
            .row
              .span3
                = session[:candidate][:pro_skill_2][:name]
                - if session[:candidate][:pro_star] == 'candidate_pro_skill_star_2'
                  .icon-star
              .span1
                = render 'progress_bar', :level => session[:candidate][:pro_skill_2][:level]
            .row
              .span3
                = session[:candidate][:pro_skill_3][:name]
                - if session[:candidate][:pro_star] == 'candidate_pro_skill_star_3'
                  .icon-star
              .span1
                = render 'progress_bar', :level => session[:candidate][:pro_skill_3][:level]
      .row
        .span4.well{ style: 'padding-bottom:0' }
          %h6 
            Qualities
          .lead
            .row
              .span3
                = session[:candidate][:inter_skill_1][:name]
                - if session[:candidate][:inter_star] == 'candidate_inter_skill_star_1'
                  .icon-star
              .span1
                = render 'progress_bar', :level => session[:candidate][:inter_skill_1][:level]
            .row
              .span3
                = session[:candidate][:inter_skill_2][:name]
                - if session[:candidate][:inter_star] == 'candidate_inter_skill_star_2'
                  .icon-star
              .span1
                = render 'progress_bar', :level => session[:candidate][:inter_skill_2][:level]
            .row
              .span3
                = session[:candidate][:inter_skill_3][:name]
                - if session[:candidate][:inter_star] == 'candidate_inter_skill_star_3'
                  .icon-star
              .span1
                = render 'progress_bar', :level => session[:candidate][:inter_skill_3][:level]
      .row
        .span4{ :style => 'margin: 20px 0 0 0; padding: 10px' }
          %h6 More about #{session[:candidate][:full_name].split.first}
          .btn.btn-large.pull-left
            .icon-download
            Download CV
          &nbsp;
          &nbsp;
          %a.linkedin-profile{ :href => '#' }
          &nbsp;
          %a.twitter-profile{ :href => '#' }
          &nbsp;
          %a.facebook-profile{ :href => '#' }
          &nbsp;
          %a.google-plus-profile{ :href => '#' }
      
  .span7
    .row
      .span6
        %a.btn.btn-primary.pull-right{ :href => params[:from_path] }
          .icon-eye-close
          Close preview
    %br/
    
    .row
      .span3.offset4
        .row
          .span1
            = image_tag 'dom.jpg'
          .span1
            %p{ :style => 'margin-top:-2px' } shared by:
            %h3{ :style => 'font-size:14px; line-height:20px' } Dominic Matheron
    %br/
    %br/
    %br/
    %br/
    %br/
    %br/
    %br/
    %br/
    
    .row
      .span5.offset1
        %h2{ :style => 'text-align:right' }
          .i.icon-comment
          &nbsp;
          = (session[:sharer].nil? || session[:sharer][:message].blank?) ? @default_message : session[:sharer][:message]
        %br/
        %br/
        .pull-right
          %a.btn.btn-gigantic.btn-danger.disabled{ :href => (candidate_demo? ? '#': recruiter_isnt_interested_path), :class => "#{'disabled' if candidate_demo?}" } Not interested
          %a.btn.btn-gigantic.btn-success.disabled{ :href => (candidate_demo? ? '#': recruiter_starts_discussion_path), :style => 'margin-right:0', :class => "#{'disabled' if candidate_demo?}" } Get in touch!
          
        %br/
        %br/
        %br/
        %br/
        %br/
        %br/
        %br/
        %br/
        %br/
        %br/
        %br/
        %br/
        
        .pull-right
          %p{ :style => 'margin-right: 5px; font-size:14px; display:inline-block' } you can also
          .btn-group{ :style => 'display:inline-block' }
            %a.btn.dropdown-toggle.disabled{ "data-toggle" => "dropdown", :href => '#', :style => 'margin-bottom: -10px', :class => "#{'disabled' if candidate_demo?}" }
              %i.icon-share
              Share this profile
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to 'Email', candidate_profile_email_share_others_path
              %li
                = link_to 'Social networks', candidate_profile_social_share_others_path

app/views/shareable/candidate_profile_public.haml
= render 'menu_candidate'

.row
  .span5
    .card
      .row
        .span4.well
          .row
            .span1
              = link_to image_tag(session[:candidate][:pic]), candidate_profile_public_path
            .span3
              %h3 
                = session[:candidate][:full_name]
              %p
                = session[:candidate][:city]+', '+session[:candidate][:country]
              %p
                = session[:candidate][:role].to_s+' at '+session[:candidate][:company]
      .row
        .span1.well
          %h6
            Experience
          .gigantic 
            = session[:candidate][:experience] == 1.to_s ? '1 yr' : session[:candidate][:experience].to_s+'yrs'
        .span3.well{ :style => 'min-height:92px; padding-right:0' }
          %h6 
            Education
          .lead 
            = session[:candidate][:education]
      .row
        .span4.well{ style: 'padding-bottom:0' }
          %h6
            Skills
          .lead
            .row
              .span3
                = session[:candidate][:pro_skill_1][:name]
                - if session[:candidate][:pro_star] == 'candidate_pro_skill_star_1'
                  .icon-star
              .span1
                = render 'progress_bar', :level => session[:candidate][:pro_skill_1][:level]
            .row
              .span3
                = session[:candidate][:pro_skill_2][:name]
                - if session[:candidate][:pro_star] == 'candidate_pro_skill_star_2'
                  .icon-star
              .span1
                = render 'progress_bar', :level => session[:candidate][:pro_skill_2][:level]
            .row
              .span3
                = session[:candidate][:pro_skill_3][:name]
                - if session[:candidate][:pro_star] == 'candidate_pro_skill_star_3'
                  .icon-star
              .span1
                = render 'progress_bar', :level => session[:candidate][:pro_skill_3][:level]
      .row
        .span4.well{ style: 'padding-bottom:0' }
          %h6 
            Qualities
          .lead
            .row
              .span3
                = session[:candidate][:inter_skill_1][:name]
                - if session[:candidate][:inter_star] == 'candidate_inter_skill_star_1'
                  .icon-star
              .span1
                = render 'progress_bar', :level => session[:candidate][:inter_skill_1][:level]
            .row
              .span3
                = session[:candidate][:inter_skill_2][:name]
                - if session[:candidate][:inter_star] == 'candidate_inter_skill_star_2'
                  .icon-star
              .span1
                = render 'progress_bar', :level => session[:candidate][:inter_skill_2][:level]
            .row
              .span3
                = session[:candidate][:inter_skill_3][:name]
                - if session[:candidate][:inter_star] == 'candidate_inter_skill_star_3'
                  .icon-star
              .span1
                = render 'progress_bar', :level => session[:candidate][:inter_skill_3][:level]
      .row
        .span4{ :style => 'margin: 20px 0 0 0; padding: 10px' }
          %h6 More about #{session[:candidate][:full_name].split.first}
          .btn.btn-large.pull-left
            .icon-download
            Download CV
          &nbsp;
          &nbsp;
          %a.linkedin-profile{ :href => '#' }
          &nbsp;
          %a.twitter-profile{ :href => '#' }
          &nbsp;
          %a.facebook-profile{ :href => '#' }
          &nbsp;
          %a.google-plus-profile{ :href => '#' }
  
  .span5.offset1
  
    - if candidate_demo?
      .row
        %a.btn.btn-primary.pull-right{ :href => candidate_profile_path, :style => 'margin:0' }
          .icon-eye-close
          Close preview

    %br/
    %br/
    %br/   
    %br/
    %br/
    %br/       
    %br/
    %br/
    %br/
    %br/
    %br/
    %br/
    
    .row
      %h2{ :style => 'text-align:right' }
        .i.icon-comment
        &nbsp;
        = session[:candidate][:catchphrase]
      %br/
      %br/
      .pull-right
        .btn-group{ :style => 'display:inline-block' }
          %a.btn.btn-gigantic.dropdown-toggle{ "data-toggle" => "dropdown", :href => '#', :style => 'padding-left: 15px; margin-bottom: -24px', :class => "#{'disabled' if candidate_demo?}"  }
            %i.icon-share
            Share
            %span.caret
          %ul.dropdown-menu
            %li
              = link_to 'Email', candidate_profile_email_share_others_path
            %li
              = link_to 'Social networks', candidate_profile_social_share_others_path
        %a.btn.btn-gigantic.btn-success{ :href => (candidate_demo? ? '#' : recruiter_starts_discussion_path), :style => 'margin-right:-5px', :class => "#{'disabled' if candidate_demo?}" } Let's talk!

app/views/shareable/candidate_profile_you_email.haml
= render 'menu_candidate'

.row
  .span5
    .card
      .row
        .span4.well
          .row
            .span1
              = link_to image_tag(session[:candidate][:pic]), candidate_profile_public_path
            .span3
              %h3 
                = session[:candidate][:full_name]
              %p
                = session[:candidate][:city]+', '+session[:candidate][:country]
              %p
                = session[:candidate][:role].to_s+' at '+session[:candidate][:company]
      .row
        .span1.well
          %h6
            Experience
          .gigantic 
            = session[:candidate][:experience] == 1.to_s ? '1 yr' : session[:candidate][:experience].to_s+'yrs'
        .span3.well{ :style => 'min-height:92px; padding-right:0' }
          %h6 
            Education
          .lead 
            = session[:candidate][:education]
      .row
        .span4.well{ style: 'padding-bottom:0' }
          %h6
            Skills
          .lead
            .row
              .span3
                = session[:candidate][:pro_skill_1][:name]
                - if session[:candidate][:pro_star] == 'candidate_pro_skill_star_1'
                  .icon-star
              .span1
                = render 'progress_bar', :level => session[:candidate][:pro_skill_1][:level]
            .row
              .span3
                = session[:candidate][:pro_skill_2][:name]
                - if session[:candidate][:pro_star] == 'candidate_pro_skill_star_2'
                  .icon-star
              .span1
                = render 'progress_bar', :level => session[:candidate][:pro_skill_2][:level]
            .row
              .span3
                = session[:candidate][:pro_skill_3][:name]
                - if session[:candidate][:pro_star] == 'candidate_pro_skill_star_3'
                  .icon-star
              .span1
                = render 'progress_bar', :level => session[:candidate][:pro_skill_3][:level]
      .row
        .span4.well{ style: 'padding-bottom:0' }
          %h6 
            Qualities
          .lead
            .row
              .span3
                = session[:candidate][:inter_skill_1][:name]
                - if session[:candidate][:inter_star] == 'candidate_inter_skill_star_1'
                  .icon-star
              .span1
                = render 'progress_bar', :level => session[:candidate][:inter_skill_1][:level]
            .row
              .span3
                = session[:candidate][:inter_skill_2][:name]
                - if session[:candidate][:inter_star] == 'candidate_inter_skill_star_2'
                  .icon-star
              .span1
                = render 'progress_bar', :level => session[:candidate][:inter_skill_2][:level]
            .row
              .span3
                = session[:candidate][:inter_skill_3][:name]
                - if session[:candidate][:inter_star] == 'candidate_inter_skill_star_3'
                  .icon-star
              .span1
                = render 'progress_bar', :level => session[:candidate][:inter_skill_3][:level]
      .row
        .span4{ :style => 'margin: 20px 0 0 0; padding: 10px' }
          %h6 More about #{session[:candidate][:full_name].split.first}
          .btn.btn-large.pull-left
            .icon-download
            Download CV
          &nbsp;
          &nbsp;
          %a.linkedin-profile{ :href => '#' }
          &nbsp;
          %a.twitter-profile{ :href => '#' }
          &nbsp;
          %a.facebook-profile{ :href => '#' }
          &nbsp;
          %a.google-plus-profile{ :href => '#' }
  
  .span5.offset1
  
    - if candidate_demo?
      .row
        %a.btn.btn-primary.pull-right{ :href => candidate_profile_email_share_you_path, :style => 'margin:0' }
          .icon-eye-close
          Close preview
  
    %br/
    %br/
    %br/   
    %br/
    %br/
    %br/
    %br/
    %br/       
    %br/
    %br/
    %br/

    %h2{ :style => 'text-align:right' }
      .i.icon-comment
      &nbsp;
      = (session[:you].nil? || session[:you][:message].blank?) ? @default_message : session[:you][:message]
    %br/
    %br/
    .pull-right
      %a.btn.btn-gigantic.btn-danger{ :href => (candidate_demo? ? '#': recruiter_says_no_path), :class => "#{'disabled' if candidate_demo?}" } Not interested
      %a.btn.btn-gigantic.btn-success{ :href => (candidate_demo? ? '#': recruiter_says_yes_path), :style => 'margin-right:-5px', :class => "#{'disabled' if candidate_demo?}" } Let's talk!
      
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      
    .pull-right
      %p{ :style => 'margin-right: 5px; font-size:14px; display:inline-block' } you can also
      .btn-group{ :style => 'display:inline-block' }
        %a.btn.dropdown-toggle{ "data-toggle" => "dropdown", :href => '#', :style => 'margin-bottom: -10px', :class => "#{'disabled' if candidate_demo?}"  }
          %i.icon-share
          Share my profile
          %span.caret
        %ul.dropdown-menu
          %li
            = link_to 'Email', candidate_profile_email_share_others_path
          %li
            = link_to 'Social networks', candidate_profile_social_share_others_path
    

app/views/shareable/candidate_says_yes.haml
= render 'menu_recruiter'

%br/

.span12
  .row
    .span2
      .row
        = render 'menu_candidate_interactions'
          
    .span8
      .row
        .span6.offset1
          .well
            .row
              .span1
                = link_to image_tag('dom.jpg'), recruiter_profile_path
              .span4
                %h5 Dominic Matheron said:
                %br/
                %h3 Hi there, I'd really like you to come on board. Is this a role you'd be interested in?
                %br/
                .btn.btn-large.btn-danger.disabled Not interested
                .btn.btn-large.btn-success.disabled Let's talk!
      .row
        .span7.offset1.success
          %i.icon-ok
            You have accepted Dominic Matheron's request.
            .pull-right.italic
              a few seconds ago
      %br/
      #dynamic_content
      .row
        .span5.offset3
          .well
            .row
              .span1
                = link_to image_tag(session[:candidate][:pic]), candidate_profile_public_path
              .span3
                %h5 Type your message:
                %textarea#message.input-xlarge{ :rows => '4' }
                %br/
                %button.btn.btn-primary{ :type => 'submit', :onclick => "add_message('#{session[:candidate][:pic]}')" } Send
                %button.btn{ :onclick => 'clean()' } Clear

app/views/shareable/recruiter_says_no.haml
= render 'menu_recruiter'

%br/

.span12
  .row
    .span2
      .row
        = render 'menu_recruiter_interactions'
          
    .span8
      .row
        .span6.offset1
          .well
            .row
              .span1
                = link_to image_tag(session[:candidate][:pic]), candidate_profile_public_path
              .span4
                %h5 #{session[:candidate][:full_name]} said:
                %br/
                %h3 Hi, I'm really keen to work for your company and would love to go over a few ideas together soon.
                %br/
                .btn.btn-large.btn-danger.disabled Not interested
                .btn.btn-large.btn-success.disabled Let's talk!
      .row
        .span7.offset1.danger
          %i.icon-remove
            You have denied #{session[:candidate][:full_name]}'s request.
          .pull-right.italic
            a few seconds ago
      %br/
      #dynamic_content
      .row
        .span5.offset3
          .well
            .row
              .span1
                = link_to image_tag('dom.jpg'), recruiter_profile_path
              .span3
                %h5 Type your message:
                %textarea#message.input-xlarge{ :rows => '4' }
                %br/
                %button.btn.btn-primary{ :type => 'submit', :onclick => "add_message('dom.jpg')" } Send
                %button.btn{ :onclick => 'clean()' } Clear  