config/routes.rb
BootstrapPrototyping::Application.routes.draw do

  get 'ajax/switch_mode'
  
  match 'candidate_signup'                      => 'shareable#candidate_signup'
  match 'candidate_profile'                     => 'shareable#candidate_profile'
  match 'candidate_profile_public'              => 'shareable#candidate_profile_public'
  match 'candidate_profile_you_email'           => 'shareable#candidate_profile_you_email'
  match 'candidate_profile_you_social'          => 'shareable#candidate_profile_you_social'
  match 'candidate_profile_others'              => 'shareable#candidate_profile_others'
  match 'candidate_profile_social_share_you'    => 'shareable#candidate_profile_social_share_you'
  match 'candidate_profile_email_share_you'     => 'shareable#candidate_profile_email_share_you'
  match 'candidate_profile_social_share_others' => 'shareable#candidate_profile_social_share_others'
  match 'candidate_profile_email_share_others'  => 'shareable#candidate_profile_email_share_others'
  match 'candidate_conversations'               => 'shareable#candidate_conversations'
  match 'candidate_conversations2'              => 'shareable#candidate_conversations2'
  match 'candidate_conversations3'              => 'shareable#candidate_conversations3'
  match 'candidate_conversations4'              => 'shareable#candidate_conversations4'
  match 'candidate_sharings'                    => 'shareable#candidate_sharings'
  match 'candidate_sharings2'                   => 'shareable#candidate_sharings2'
  match 'candidate_sharings3'                   => 'shareable#candidate_sharings3'
  match 'candidate_matches'                     => 'shareable#candidate_matches'
  match 'candidate_matches2'                    => 'shareable#candidate_matches2'
  match 'candidate_matches3'                    => 'shareable#candidate_matches3'
  match 'candidate_matches4'                    => 'shareable#candidate_matches4'
  match 'candidate_isnt_interested'             => 'shareable#candidate_isnt_interested'
  match 'candidate_says_yes'                    => 'shareable#candidate_says_yes'
  match 'candidate_says_no'                     => 'shareable#candidate_says_no'
  match 'recruiter_signup'                      => 'shareable#recruiter_signup'
  match 'recruiter_profile'                     => 'shareable#recruiter_profile'
  match 'recruiter_says_yes'                    => 'shareable#recruiter_says_yes'
  match 'recruiter_says_no'                     => 'shareable#recruiter_says_no'
  match 'recruiter_starts_discussion'           => 'shareable#recruiter_starts_discussion'
  match 'recruiter_isnt_interested'             => 'shareable#recruiter_isnt_interested'
  match 'recruiter_profile_1_public'            => 'shareable#recruiter_profile_1_public'
  match 'recruiter_profile_1_others'            => 'shareable#recruiter_profile_1_others'
  match 'recruiter_profile_1_you'               => 'shareable#recruiter_profile_1_you'
  match 'recruiter_profile_2_public'            => 'shareable#recruiter_profile_2_public'
  match 'recruiter_profile_3_public'            => 'shareable#recruiter_profile_3_public'
  match 'recruiter_profile_4_public'            => 'shareable#recruiter_profile_4_public'
  match 'recruiter_conversations'               => 'shareable#recruiter_conversations'
  match 'recruiter_conversations2'              => 'shareable#recruiter_conversations2'
  match 'recruiter_conversations3'              => 'shareable#recruiter_conversations3'
  match 'recruiter_conversations4'              => 'shareable#recruiter_conversations4'
  match 'recruiter_sharings'                    => 'shareable#recruiter_sharings'
  match 'recruiter_sharings2'                   => 'shareable#recruiter_sharings2'
  match 'recruiter_sharings3'                   => 'shareable#recruiter_sharings3'

  root :to => 'pages#dashboard'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang='en'>

  <head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <title><%= page_title %></title>
    <%= csrf_meta_tags %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src='http://html5shim.googlecode.com/svn/trunk/html5.js' type='text/javascript'></script>
    <![endif]-->
    <%= stylesheet_link_tag 'application', :media => 'all' %>
    <link href='images/favicon.ico' rel='shortcut icon'>
    <link href='images/apple-touch-icon.png' rel='apple-touch-icon'>
    <link href='images/apple-touch-icon-72x72.png' rel='apple-touch-icon' sizes='72x72'>
    <link href='images/apple-touch-icon-114x114.png' rel='apple-touch-icon' sizes='114x114'>
  </head>
  
  <body>  
    <div class='navbar navbar-fixed-top'>
      <div class='navbar-inner'>
        <div class='container-fluid'>
          <%= link_to "Engaccino", (session[:mode] == 'demo' ? '#' : root_path), :class => 'brand' %>
          <% if session[:mode] == 'demo' %>
            <ul class='nav'>
              <% if session[:candidate_demo] %>
                <li class="<%= 'active' if request.fullpath.include?('candidate_profile') %>">
                  <%= link_to 'Profile', candidate_profile_path %>
                </li>
                </li>
                <li <%= "class='active'" unless request.fullpath.include?('candidate_profile') || request.fullpath.include?('signup') %>>
                  <%= link_to 'Interactions', candidate_conversations_path %>
                </li>
              <% elsif session[:recruiter_demo] %>
                <li <%= "class='active'" if request.fullpath.include?('recruiter_profile') %>>
                  <%= link_to 'Profile', recruiter_profile_path %>
                </li>
                <li <%= "class='active'" unless request.fullpath.include?('recruiter_profile') %>>
                  <%= link_to 'Interactions', recruiter_conversations_path %>
                </li>
              <% end %>
            </ul>
            <ul class="nav pull-right">
              <li>
                <a href='#', onclick="switch_mode('dev')">
                  <i class="icon-wrench icon-white"></i>
                  dev mode
                </a>
              </li>
            </ul>
          <% else %>
            <ul class='nav'>
              <li class='dropdown'>
                <a href='#' class='dropdown-toggle' data-toggle='dropdown'>Shareable profile<b class='caret'></b></a>
                <ul class='dropdown-menu'>  
                  <li>
                    <%= link_to 'Candidate', candidate_signup_path %>
                  </li>
                  <li>
                    <%= link_to 'Recruiter', recruiter_signup_path %>
                  </li>
                </ul>
              </li>
            </ul>
            <% if request.fullpath != root_path %>
              <ul class="nav pull-right">
                <li>
                  <a href='#', onclick="switch_mode('demo')">
                    <i class="icon-eye-open icon-white"></i>
                    demo mode
                  </a>
                </li>
              </ul>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    
    <% flash.each do |key, value| %>
      <div id="flash" class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>
    
    <%= yield %>

    <%= javascript_include_tag 'application' %>

  </body>
  
</html>